package com.minecartvisualizer.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.CyclingListControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;

import java.util.List;

public class MinecartVisualizerConfigScreen {

    public static Screen create(Screen parent) {
        MinecartVisualizerConfig config = MinecartVisualizerConfig.getInstance();

        return YetAnotherConfigLib.createBuilder()
                .title(Text.translatable("yacl.title.minecart_visualizer"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("yacl.category.main_settings"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("yacl.group.main_render"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.enable_visualization"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.enable_visualization.desc")))
                                        .binding(false, () -> config.enableMinecartVisualization, v -> config.enableMinecartVisualization = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.always_facing"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.always_facing.desc")))
                                        .binding(true, () -> config.alwaysFacingThePlayer, v -> config.alwaysFacingThePlayer = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.glowing_tracking"))
                                        .binding(true, () -> config.glowingTrackingMinecart, v -> config.glowingTrackingMinecart = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("yacl.option.inventory_cols"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.inventory_cols.desc")))
                                        .binding(5, () -> config.inventoryCols, v -> config.inventoryCols = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(1, 9)
                                                .step(1))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.fold_inventory"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.fold_inventory.desc")))
                                        .binding(true, () -> config.foldInventory, v -> config.foldInventory = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.auto_size_columns"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.auto_size_columns.desc")))
                                        .binding(true, () -> config.autoSizeColumns, v -> config.autoSizeColumns = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.merge_stacking_info"))
                                        .binding(true, () -> config.mergeStackingMinecartInfo, v -> config.mergeStackingMinecartInfo = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("yacl.option.max_slots"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.max_slots.desc")))
                                        .binding(0, () -> config.maxInventorySlotsToRender, v -> config.maxInventorySlotsToRender = v)
                                        .controller(opt -> IntegerFieldControllerBuilder.create(opt)
                                                .min(0)
                                                .max(1000)
                                        )
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("yacl.option.render_distance"))
                                        .binding(32, () -> config.infoRenderDistance, v -> config.infoRenderDistance = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(8, 32).step(1))
                                        .build())
                                .option(Option.<MinecartVisualizerConfig.TimeUnit>createBuilder()
                                        .name(Text.translatable("yacl.option.tracker_time_unit"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.tracker_time_unit.desc")))
                                        .binding(
                                                MinecartVisualizerConfig.TimeUnit.SECOND,
                                                () -> config.trackerTimeUnit,
                                                v -> config.trackerTimeUnit = v
                                        )
                                        .controller(opt -> CyclingListControllerBuilder.create(opt)
                                                .values(MinecartVisualizerConfig.TimeUnit.values())
                                                .formatValue(unit -> Text.literal(unit.getLabel()))
                                        )
                                        .build())
                                .option(Option.<MinecartVisualizerConfig.SpeedUnit>createBuilder()
                                        .name(Text.translatable("yacl.option.speed_unit"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.speed_unit.desc")))
                                        .binding(
                                                MinecartVisualizerConfig.SpeedUnit.METERS_PER_SECOND,
                                                () -> config.speedUnit,
                                                v -> config.speedUnit = v
                                        )
                                        .controller(opt -> CyclingListControllerBuilder.create(opt)
                                                .values(MinecartVisualizerConfig.SpeedUnit.values())
                                                .formatValue(unit -> Text.literal(unit.getLabel()))
                                        )
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("yacl.group.hopper_filter"))
                                .description(OptionDescription.of(Text.translatable("yacl.group.hopper_filter.desc")))
                                .collapsed(true)
                                .options(List.of(
                                        createSlotOption(0),
                                        createSlotOption(1),
                                        createSlotOption(2),
                                        createSlotOption(3),
                                        createSlotOption(4)
                                ))
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("yacl.group.text_info"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.enable_text"))
                                        .binding(true, () -> config.enableInfoTextDisplay, v -> config.enableInfoTextDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_pos"))
                                        .binding(true, () -> config.enablePosTextDisplay, v -> config.enablePosTextDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_speed"))
                                        .binding(true, () -> config.enableSpeedTextDisplay, v -> config.enableSpeedTextDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_velocity"))
                                        .binding(true, () -> config.enableVelocityTextDisplay, v -> config.enableVelocityTextDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_yaw"))
                                        .binding(true, () -> config.enableYawTextDisplay, v -> config.enableYawTextDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.direction"))
                                        .binding(true, () -> config.enableDirectionDisplay, v -> config.enableDirectionDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_stacked_count"))
                                        .binding(true, () -> config.enableStackedCountDisplay, v -> config.enableStackedCountDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_signal_strength"))
                                        .binding(true, () -> config.enableSignalStrengthDisplay, v -> config.enableSignalStrengthDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_tracker_runtime"))
                                        .binding(true, () -> config.enableTrackerRuntimeDisplay, v -> config.enableTrackerRuntimeDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.show_short_id"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.show_short_id.desc")))
                                        .binding(true, () -> config.enableShortIdDisplay, v -> config.enableShortIdDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("yacl.option.accuracy"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.accuracy.desc")))
                                        .binding(3, () -> config.accuracy, v -> config.accuracy = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 10).step(1))
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("yacl.group.special_minecarts"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.hopper_range"))
                                        .binding(true, () -> config.renderHopperRanges, v -> config.renderHopperRanges = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.highlight_targets"))
                                        .binding(true, () -> config.highlightExtractionTargets, v -> config.highlightExtractionTargets = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.hopper_locked"))
                                        .binding(true, () -> config.enableHopperMinecartEnableDisplay, v -> config.enableHopperMinecartEnableDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.hopper_inventory"))
                                        .binding(true, () -> config.enableHopperMinecartInventoryDisplay, v -> config.enableHopperMinecartInventoryDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.item_stack_count"))
                                        .binding(true, () -> config.enableItemStackCountDisplay, v -> config.enableItemStackCountDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.tnt_fuse"))
                                        .binding(true, () -> config.enableTNTFuseTicksDisplay, v -> config.enableTNTFuseTicksDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.tnt_wobble"))
                                        .binding(true, () -> config.enableTNTWobbleDisplay, v -> config.enableTNTWobbleDisplay = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("yacl.group.track"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.track_trail"))
                                        .binding(true, () -> config.trackMinecartTrail, v -> config.trackMinecartTrail = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("yacl.option.max_trail_points"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.max_trail_points.desc")))
                                        .binding(200, () -> config.maxTrailPoints, v -> config.maxTrailPoints = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 1000).step(50))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.output_slot_change"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.output_slot_change.desc")))
                                        .binding(true, () -> config.outputWhenSlotChange, v -> config.outputWhenSlotChange = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.output_destroyed"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.output_destroyed.desc")))
                                        .binding(true, () -> config.outputWhenDestroyed, v -> config.outputWhenDestroyed = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.output_on_increase"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.output_on_increase.desc")))
                                        .binding(true, () -> config.outputOnIncrease, v -> config.outputOnIncrease = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.output_on_decrease"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.output_on_decrease.desc")))
                                        .binding(true, () -> config.outputOnDecrease, v -> config.outputOnDecrease = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.print_inventory"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.print_inventory.desc")))
                                        .binding(true, () -> config.printInventory, v -> config.printInventory = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.print_duration"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.print_duration.desc")))
                                        .binding(true, () -> config.printDuration, v -> config.printDuration = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.print_coordinates"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.print_coordinates.desc")))
                                        .binding(true, () -> config.printPosition, v -> config.printPosition = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.tracking_by_dye"))
                                        .description(OptionDescription.of(Text.translatable("yacl.option.tracking_by_dye.desc")))
                                        .binding(true, () -> config.trackingByDye, v -> config.trackingByDye = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("yacl.option.track_tnt"))
                                        .binding(true, () -> config.trackTNTMinecart, v -> config.trackTNTMinecart = v)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .save(MinecartVisualizerConfig.HANDLER::save)
                .build()
                .generateScreen(parent);
    }

    private static Option<Boolean> createSlotOption(int index) {
        MinecartVisualizerConfig config = MinecartVisualizerConfig.getInstance();
        return Option.<Boolean>createBuilder()
                .name(Text.translatable("yacl.minecartvisualizer.text.slot" ).append(" " + (index + 1)))
                .binding(true, () -> config.hopperSlotFilter[index], v -> config.hopperSlotFilter[index] = v)
                .controller(TickBoxControllerBuilder::create)
                .build();
    }

}